CREATE database INFORMATION;
	CREATE TABLE GOSTOS(
		COMIDA VARCHAR(50) NOT NULL,
		FILME VARCHAR(50) NOT NULL,
		SERIE VARCHAR(50) NOT NULL,
		ID INT AUTO_INCREMENT NOT NULL,

		CONSTRAINT ID_PK PRIMARY KEY (ID));

	CREATE TABLE USUARIO(
		NOME VARCHAR(50) NOT NULL,
		SENHA VARCHAR(50) NOT NULL,
		PS_ID INT AUTO_INCREMENT NOT NULL,
		PS_GO_ID VARCHAR(50) NOT NULL,
		CONSTRAINT PS_PK PRIMARY KEY (PS_ID)
		CONSTRAINT PS_PK_FK FOREIGN KEY (PS_GO_ID) REFERENCES GOSTOS(ID));