CREATE database lll;
	CREATE TABLE DADOS(
		DA_NOME VARCHAR(30) NOT NULL,
		DA_FILME VARCHAR(30) NOT NULL,
		DA_SERIE VARCHAR(30) NOT NULL,

		DA_ID INT AUTO_INCREMENT NOT NULL,
		

		CONSTRAINT DA_PK PRIMARY KEY (DA_ID));
