CREATE database INFORMATION;

	CREATE TABLE USUARIO(
		NOME VARCHAR(50) NOT NULL,
		SENHA VARCHAR(50) NOT NULL,
		US_ID INT AUTO_INCREMENT NOT NULL,
		US_GO_ID VARCHAR(50) NOT NULL,

		CONSTRAINT US_PK PRIMARY KEY (US_ID));


	CREATE TABLE GOSTOS(
		COMIDA VARCHAR(50) NOT NULL,
		FILME VARCHAR(50) NOT NULL,
		SERIE VARCHAR(50) NOT NULL,
		ID INT AUTO_INCREMENT NOT NULL,
		US_GO_ID INT NOT NULL,

		CONSTRAINT ID_PK PRIMARY KEY (ID)
		CONSTRAINT US_PK_FK FOREIGN KEY GOSTOS(US_GO_ID) REFERENCES USUARIO(US_ID));